### ISSUE TITLE
OnTap not firing on current week display

### ISSUE THREAD

**Issue by jovy7** [SimformSolutionsPvtLtd/flutter_calendar_view#338]
OnTap Event not firing when you are in the current week of the weekview(). Previous weeks and Future weeks are ok.

**Comment by AndreLuizNogueira** [comment]
I am also facing this issue on 1.1.0. tried 1.0.4 and it worked

**Comment by AndreLuizNogueira** [comment]
For anyone experiencing this error, it has already been fixed, just add a dependency override

```
dependency_overrides: 
  calendar_view:
    git:
      url: https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view.git
```
