### ISSUE TITLE
Missing "clear" method inside EventController

### ISSUE THREAD

**Issue by Paroca72** [SimformSolutionsPvtLtd/flutter_calendar_view#467]
Hello,

I have installed the latest version of this package (calendar_view: ^1.4.0).
Reading the documentation It should be a "clear" method inside the EventController but there is not.

![Image](https://github.com/user-attachments/assets/0a5d3986-5ddd-4587-830c-3b4503a01ea4)

Thanks
Sam

**Comment by rashi-simform** [comment]
Hi @Paroca72,
This issue is fixed in the master branch but not yet released. 
In the meantime, you can use following workaround.
 
```
flutter_calender_view:
  git:
    url: https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view.git
    ref: master
```
